# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/testpower.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Org1
        Name: Org1MSP

        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/org1.testpower.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"

        AnchorPeers:
            - Host: peer0.org1.testpower.com
              Port: 1051

    - &Org2
        Name: Org2MSP

        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/org2.testpower.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"

        AnchorPeers:
            - Host: peer0.org2.testpower.com
              Port: 2051

    - &Org3
        Name: Org3MSP

        ID: Org3MSP

        MSPDir: crypto-config/peerOrganizations/org3.testpower.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org3MSP.admin')"

        AnchorPeers:
            - Host: peer0.org3.testpower.com
              Port: 3051
        
    - &Org4
        Name: Org4MSP

        # ID to load the MSP definition as
        ID: Org4MSP

        MSPDir: crypto-config/peerOrganizations/org4.testpower.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org4MSP.admin', 'Org4MSP.peer', 'Org4MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org4MSP.admin', 'Org4MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org4MSP.admin')"

        AnchorPeers:
            - Host: peer0.org4.testpower.com
              Port: 4051

Capabilities:

    Channel: &ChannelCapabilities

        V1_4_2: true

        V1_3: false

        V1_1: false

    Orderer: &OrdererCapabilities

        V1_4_2: true

        V1_1: false

    Application: &ApplicationCapabilities

        V1_4_2: true

        V1_3: false

        V1_2: false

        V1_1: false

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
            - Host: orderer1.testpower.com
              Port: 7450
              ClientTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer1.testpower.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer1.testpower.com/tls/server.crt
            - Host: orderer2.testpower.com
              Port: 8450
              ClientTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer2.testpower.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer2.testpower.com/tls/server.crt
            - Host: orderer3.testpower.com
              Port: 9450
              ClientTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer3.testpower.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer3.testpower.com/tls/server.crt
            - Host: orderer4.testpower.com
              Port: 10450
              ClientTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer4.testpower.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer4.testpower.com/tls/server.crt
            - Host: orderer5.testpower.com
              Port: 11450
              ClientTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer5.testpower.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/testpower.com/orderers/orderer5.testpower.com/tls/server.crt
    Addresses:
        - orderer1.testpower.com:7450
        - orderer2.testpower.com:8450
        - orderer3.testpower.com:9450
        - orderer4.testpower.com:10450
        - orderer5.testpower.com:11450

    BatchTimeout: 1s

    BatchSize:

        MaxMessageCount: 100

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 1024 KB

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    testpowerMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Org4

    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
                - *Org4
            Capabilities:
                <<: *ApplicationCapabilities


    ThreeOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
                - *Org4
            Capabilities:
                <<: *ApplicationCapabilities
