FROM xnba-39-107-230-170-p-oo-o1:v1


#当前目录所有文件copy进去
COPY ./channel-artifacts/genesis.block /var/hyperledger/orderer/orderer.genesis.block
COPY ./crypto-config/ordererOrganizations/testpower.com/orderers/orderer1.testpower.com/msp /var/hyperledger/orderer/msp
COPY ./crypto-config/ordererOrganizations/testpower.com/orderers/orderer1.testpower.com/tls /var/hyperledger/orderer/tls

#设置环境变量


#进入工作目录
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric


#端口 
EXPOSE 7450

#启动
ENTRYPOINT ["orderer"]

#cmd

