FROM hyperledger/fabric-peer:1.4.2

#进入工作目录
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric/peer

#创世快
COPY ./channel-artifacts/genesis.block /var/hyperledger/orderer/orderer.genesis.block
#msp
COPY ./crypto-config/peerOrganizations/org1.testpower.com/peers/peer0.org1.testpower.com/msp /etc/hyperledger/fabric/msp
#tls
COPY ./crypto-config/peerOrganizations/org1.testpower.com/peers/peer0.org1.testpower.com/tls /etc/hyperledger/fabric/tls

COPY ./crypto-config/peerOrganizations/org1.testpower.com/peers/peer0.org1.testpower.com/users /etc/hyperledger/fabric/users

COPY ./channel-artifacts /opt/gopath/src/github.com/hyperledger/fabric/peer


#设置环境变量 
ENV CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
ENV FABRIC_LOGGING_SPEC=DEBUG
ENV CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=neet_byfn
ENV CORE_CHAINCODE_EXECUTETIMEOUT=300s
ENV FABRIC_CFG_PATH=/etc/hyperledger/fabric
ENV GODEBUG=netdns=go
ENV GOPATH=/opt/gopath
#修改参数
ENV CORE_PEER_ID=peer0.org1.testpower.com
ENV CORE_PEER_LOCALMSPID=Org1MSP

ENV CORE_PEER_LISTENADDRESS=0.0.0.0:1051
ENV CORE_PEER_ADDRESS=peer0.org1.testpower.com:1051
ENV CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.testpower.com:1051
ENV CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.testpower.com:1151

ENV CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1052
ENV CORE_PEER_CHAINCODEADDRESS=peer0.org1.testpower.com:1052


ENV CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
ENV CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
ENV CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt

ENV CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/users/Admin@org1.newpower.com/msp

ENV CORE_PEER_PROFILE_ENABLED=true
ENV CORE_PEER_GOSSIP_USELEADERELECTION=true
ENV CORE_PEER_TLS_ENABLED=true
ENV CORE_PEER_GOSSIP_ORGLEADER=false

#端口 
EXPOSE 1051
EXPOSE 1052
EXPOSE 1151

#启动
ENTRYPOINT ["peer"]

#cmd
CMD ["node","start"]

