FROM hyperledger/fabric-peer:1.4.2

#进入工作目录
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric/peer

#创世快
COPY ./channel-artifacts/genesis.block /var/hyperledger/orderer/orderer.genesis.block
#msp
COPY ./crypto-config/peerOrganizations/org1.testpower.com/peers/peer3.org1.testpower.com/msp /etc/hyperledger/fabric/msp
#tls
COPY ./crypto-config/peerOrganizations/org1.testpower.com/peers/peer3.org1.testpower.com/tls /etc/hyperledger/fabric/tls

#设置环境变量 
ENV CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
ENV FABRIC_LOGGING_SPEC=INFO
ENV CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mybridge
ENV CORE_CHAINCODE_EXECUTETIMEOUT=300s
ENV FABRIC_CFG_PATH=/etc/hyperledger/fabric
ENV GODEBUG=netdns=go
ENV GOPATH=/opt/gopath
#修改参数
ENV CORE_PEER_ID=peer3.org1.testpower.com
ENV CORE_PEER_LOCALMSPID=Org1MSP

ENV CORE_PEER_LISTENADDRESS=0.0.0.0:1351
ENV CORE_PEER_ADDRESS=peer3.org1.testpower.com:1351
ENV CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.testpower.com:1351

ENV CORE_PEER_GOSSIP_BOOTSTRAP=peer3.org1.testpower.com:1251

ENV CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1352
ENV CORE_PEER_CHAINCODEADDRESS=peer3.org1.testpower.com:1352


ENV CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
ENV CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
ENV CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt

ENV CORE_PEER_PROFILE_ENABLED=true
ENV CORE_PEER_GOSSIP_USELEADERELECTION=true
ENV CORE_PEER_TLS_ENABLED=true
ENV CORE_PEER_GOSSIP_ORGLEADER=false

#端口 
EXPOSE 1351
EXPOSE 1352
EXPOSE 1251

#启动
ENTRYPOINT ["peer"]

#cmd
CMD ["node","start"]

