FROM hyperledger/fabric-peer:1.4.2
#进入工作目录
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric/peer
#创世快
# COPY ./channel-artifacts/genesis.block /var/hyperledger/orderer/orderer.genesis.block
COPY ./crypto-config/peerOrganizations/org1.bookstore.com/peers/peer1.org1.bookstore.com/msp /etc/hyperledger/fabric/msp
COPY ./crypto-config/peerOrganizations/org1.bookstore.com/peers/peer1.org1.bookstore.com/tls /etc/hyperledger/fabric/tls
# COPY ./crypto-config/peerOrganizations/org1.bookstore.com/users /etc/hyperledger/fabric/users
COPY ./crypto-config/ /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto

#设置环境变量 
ENV CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
ENV CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mybridge
ENV FABRIC_LOGGING_SPEC=DEBUG
ENV CORE_PEER_TLS_ENABLED=false
ENV CORE_PEER_GOSSIP_USELEADERELECTION=true
ENV CORE_PEER_GOSSIP_ORGLEADER=false
ENV CORE_PEER_PROFILE_ENABLED=true
ENV FABRIC_CFG_PATH=/etc/hyperledger/fabric
ENV CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
ENV CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
ENV CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

ENV CORE_CHAINCODE_EXECUTETIMEOUT=300s
ENV GODEBUG=netdns=go

ENV CORE_PEER_ID=peer1.org1.bookstore.com
ENV CORE_PEER_ADDRESS=peer1.org1.bookstore.com:1151
ENV CORE_PEER_LISTENADDRESS=0.0.0.0:1151
ENV CORE_PEER_CHAINCODEADDRESS=peer1.org1.bookstore.com:1152
ENV CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1152
ENV CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.bookstore.com:1151
ENV CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.bookstore.com:1051
ENV CORE_PEER_LOCALMSPID=Org1MSP
# ENV CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/users/User1@org1.bookstore.com/msp


ENV CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.bookstore.com:1151
ENV CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
#端口 
EXPOSE 1151

#启动
ENTRYPOINT ["peer"]
#cmd
CMD ["node","start"]

