FROM hyperledger/fabric-peer:1.4.2

#进入工作目录
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric

#创世快
COPY /mnt/d/gopath/src/dockertag/channel-artifacts/genesis.block /var/hyperledger/orderer/orderer.genesis.block
#msp
COPY ./crypto-config/peerOrganizations/org4.testpower.com/peers/peer0.org4.testpower.com/msp /etc/hyperledger/fabric/msp
#tls
COPY ./crypto-config/peerOrganizations/org4.testpower.com/peers/peer0.org4.testpower.com/tls /etc/hyperledger/fabric/tls

#设置环境变量 
ENV CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
ENV FABRIC_LOGGING_SPEC=INFO
ENV CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=neet_byfn
ENV CORE_CHAINCODE_EXECUTETIMEOUT=300s
ENV FABRIC_CFG_PATH=/etc/hyperledger/fabric
ENV GODEBUG=netdns=go
ENV GOPATH=/opt/gopath
#修改参数
ENV CORE_PEER_ID=peer0.org4.testpower.com
ENV CORE_PEER_LOCALMSPID=Org4MSP

ENV CORE_PEER_LISTENADDRESS=0.0.0.0:4051
ENV CORE_PEER_ADDRESS=peer0.org4.testpower.com:4051
ENV CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.testpower.com:4051
ENV CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.testpower.com:4151

ENV CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4052
ENV CORE_PEER_CHAINCODEADDRESS=peer0.org4.testpower.com:4052


ENV CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
ENV CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
ENV CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt

ENV CORE_PEER_PROFILE_ENABLED=true
ENV CORE_PEER_GOSSIP_USELEADERELECTION=true
ENV CORE_PEER_TLS_ENABLED=true
ENV CORE_PEER_GOSSIP_ORGLEADER=false

#端口 
EXPOSE 4051
EXPOSE 4052
EXPOSE 4151

#启动
ENTRYPOINT ["peer"]

#cmd
CMD ["node","start"]

